// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Alten_test.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

        modelBuilder.Entity("Alten_test.Data.Models.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Category")
                    .HasColumnType("TEXT");

                b.Property<string>("Code")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<string>("InventoryStatus")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<int>("Price")
                    .HasColumnType("INTEGER");

                b.Property<int>("Quantity")
                    .HasColumnType("INTEGER");

                b.Property<string>("image")
                    .HasColumnType("TEXT");

                b.Property<int>("rating")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("Products");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Name = "Post 1",
                        Price = 0,
                        Quantity = 0,
                        rating = 0
                    },
                    new
                    {
                        Id = 2,
                        Name = "Post 2",
                        Price = 0,
                        Quantity = 0,
                        rating = 0
                    },
                    new
                    {
                        Id = 3,
                        Name = "Post 3",
                        Price = 0,
                        Quantity = 0,
                        rating = 0
                    },
                    new
                    {
                        Id = 4,
                        Name = "Post 4",
                        Price = 0,
                        Quantity = 0,
                        rating = 0
                    },
                    new
                    {
                        Id = 5,
                        Name = "Post 5",
                        Price = 0,
                        Quantity = 0,
                        rating = 0
                    },
                    new
                    {
                        Id = 6,
                        Name = "Post 6",
                        Price = 0,
                        Quantity = 0,
                        rating = 0
                    });
            });
#pragma warning restore 612, 618
    }
}
